In [1]:
#importación de modulos necesarios
import pandas as pd
import math
import random as rnd

In [2]:
#Carga la base de datos en un df distinto por hoja para poder manipularlo
tiempo_vista_df=pd.read_excel("Base_de_datos.xlsx",sheet_name="Watch time")
fuente_trafico_df=pd.read_excel("Base_de_datos.xlsx",sheet_name="Traffic source")
tipo_rep_df=pd.read_excel("Base_de_datos.xlsx",sheet_name="Playback location")
demografia_df=pd.read_excel("Base_de_datos.xlsx",sheet_name="Demographics")

In [6]:
#Función que regresa el tiempo total de vista del canal por día dado.
def tiempo_vista_dia(x):
    tiempo=0
    for i in range(len(tiempo_vista_df['Watch time (minutes)'])):
        if tiempo_vista_df['Date'] == x:
            tiempo+= tiempo_vista_df['Watch time (minutes)'][i]
    return tiempo
#Función auxiliar que segmenta los datos por día dado
def datos_dia(dia,mes,dia_final=0,mes_final=0):
    final=0
    inicio=0
    contador=0
    if mes_final ==0:
        mes_final=mes
    if dia_final ==0:
        dia_final=dia
    for i in range(len(tiempo_vista_df['Date'])):
        if tiempo_vista_df['Date'][i].month >= mes and tiempo_vista_df['Date'][i].month <= mes_final:
            if tiempo_vista_df['Date'][i].day >= dia and tiempo_vista_df['Date'][i].day <= dia_final:
                final =i
                contador+=1
    inicio=final-contador
    df_dia=tiempo_vista_df[inicio:final]
    return df_dia

# Función que regresa en una lista  los paises en donde se vio el canal.
def paises():
    paises_prev=[]
    for i in range(len(tiempo_vista_df['Geography'])):
        paises_prev.append(tiempo_vista_df['Geography'][i])
    paises_conj=set(paises_prev)
    paises=list(paises_conj)
    return paises
 
# Función que regresa el pais donde se vio el canal por más minutos por día, rango de días
def pais_minutos_dia(dia,mes,dia_final=dia,mes_final=mes):
    minutos=[]
    df_dia=datos_dia(dia,mes, dia_final, mes_final)
    for i in range(len(df_dia['Watch time (minutes)'])):
        minutos.append(df_dia['Watch time (minutes)'][i])
    maximo=df_dia['Geography'][maximo.index(max(maximo))]
    return maximo

# Función que regresa el número de minutos totales, número de vistas o promedio de duración por vista del pais dado
# en un día, rango de días , mes o rango de meses dados

def info_pais(pais,dia,mes,minu=0,nvistas=0,prom=0,dia_final=dia,mes_final=mes):
        df_datos=datos_dia(dia,mes,dia_final,mes_final)
        if nvistas ==1:
            numero=0
            for i in range(len(df_datos["Views"])):
                if df_datos["Geography"][i]== pais:
                    numero= numero + df_datos["Views"]
        if prom == 1:
            promedio=0
            for i in range(len(df_datos['Average view duration (minutes)'])):
                if df_datos["Geography"][i]== pais:
                    promedio+= ddf_atos['Average view duration (minutes)']
        if minu == 1:
            minutos=0
            for i in range(len(datos['Watch time (minutes)'])):
                if df_datos["Geography"][i]== pais:
                    minutos= minutos + df_datos['Watch time (minutes)']
        return numero,promedio,minutos ##truena si no se quieren los tres porque al  menos una no estara definida
    
#Función que dado un mes, regrese el día que más suscriptores se ganaron
def sus_ganados(mes):
    indices=[]
    suscriptores=[]
    for i in range(len(tiempo_vista_df['Subscribers gained'])):
        if tiempo_vista_df['Date'][i].month == mes:
            suscriptores.append(tiempo_vista_df['Subscribers gained'][i])
            indices.append(i)
    indice_maximo=suscriptores.index(max(suscriptores))
    indice=indices[indice]
    maximo=tiempo_vista_df['Date'][indice]
    return maximo

def sus_perdidos(mes):
    indices=[]
    suscriptores=[]
    for i in range(len(tiempo_vista_df['Subscribers lost'])):
        if tiempo_vista_df['Date'][i].month == mes:
            suscriptores.append(tiempo_vista_df['Subscribers lost'][i])
            indices.append(i)
    if max(suscriptores) !=0:
        indice_maximo=suscriptores.index(max(suscriptores))
        indice=indices[indice]
        maximo=tiempo_vista_df['Date'][indice]
        return maximo
    else:
        print("No se perdieron suscriptores en el mes dado")

In [21]:
tiempo_vista_df['Views']

,Date,Geography,Geography ID,Channel display name,Channel ID,Watch time (minutes),Views,Average view duration (minutes),Comments,Likes,Dislikes,Subscribers gained,Subscribers lost
0,2019-01-29 16:00:00,Argentina,AR,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,828,139,6.0,0,0,0,0,0
1,2019-01-29 16:00:00,Bolivia,BO,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,282,44,6.4,0,0,0,0,0
2,2019-01-29 16:00:00,Brazil,BR,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,72,33,2.2,0,0,0,0,0
3,2019-01-29 16:00:00,Chile,CL,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,423,69,6.1,0,0,0,0,0
4,2019-01-29 16:00:00,Colombia,CO,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,1062,154,6.9,0,0,0,12,0

In [3]:
fuente_trafico_df

,Date,Geography,Geography ID,Traffic source type,Channel display name,Channel ID,Watch time (minutes),Views,Average view duration (minutes)
0,2019-01-29 16:00:00,Argentina,AR,Browse features,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,158,38,4.2
1,2019-01-29 16:00:00,Argentina,AR,Suggested videos,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,414,57,7.3
2,2019-01-29 16:00:00,Bolivia,BO,Browse features,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,72,13,5.6
3,2019-01-29 16:00:00,Brazil,BR,Browse features,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,41,18,2.3
4,2019-01-29 16:00:00,Chile,CL,Browse features,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,64,13,4.9

In [4]:
tiempo_vista_df.head()

,Date,Geography,Geography ID,Channel display name,Channel ID,Watch time (minutes),Views,Average view duration (minutes),Comments,Likes,Dislikes,Subscribers gained,Subscribers lost
0,2019-01-29 16:00:00,Argentina,AR,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,828,139,6.0,0,0,0,0,0
1,2019-01-29 16:00:00,Bolivia,BO,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,282,44,6.4,0,0,0,0,0
2,2019-01-29 16:00:00,Brazil,BR,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,72,33,2.2,0,0,0,0,0
3,2019-01-29 16:00:00,Chile,CL,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,423,69,6.1,0,0,0,0,0
4,2019-01-29 16:00:00,Colombia,CO,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,1062,154,6.9,0,0,0,12,0

,Viewer gender,Viewer age,Channel display name,Channel ID,Views,Watch time (minutes)
0,Female,18–24 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,0.2,0.2
1,Female,25–34 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,1.0,1.1
2,Female,35–44 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,0.2,0.1
3,Male,13–17 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,1.7,1.3
4,Male,18–24 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,24.2,21.7
5,Male,25–34 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,35.0,35.8
6,Male,35–44 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,22.6,23.9
7,Male,45–54 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,10.9,11.2
8,Male,55–64 years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,3.9,4.6
9,Male,65+ years,OFFBEAT MX,Y2rX3U58I5omg9k0wuERzg,0.2,0.1

In [10]:
x=[1,2,3,4,5,6]
max(x)
x.index(max(x))

5